원샘플 티테스트

In [ ]:
# 통계흐름


# 평균 계산
# 표준오차(se)
# 신뢰구간 확인
# t-test

In [ ]:
# 가정 >>> 사용자 체류시간의 평균은 5분이다.

import numpy as np
import pandas as pd

# 사용자 체류시간 (분)
df = pd.DataFrame({
    "session_time": [5.5, 6.2, 4.8, 5.9, 6.5, 5.1, 5.8, 6.0, 5.7, 6.3,
                     5.4, 6.1, 5.6, 5.9, 6.2, 5.3, 5.8, 6.4, 6.0, 5.7]
})

In [ ]:
df

    session_time
0            5.5
1            6.2
2            4.8
3            5.9
4            6.5
5            5.1
6            5.8
7            6.0
8            5.7
9            6.3
10           5.4
11           6.1
12           5.6
13           5.9
14           6.2
15           5.3
16           5.8
17           6.4
18           6.0
19           5.7

In [ ]:
# 기본 통계확인
# 주로 std, min, max가장 많이 확인

df.describe()

# 현재 데이터에서 std가 0.43이고 mean이 5.8
# std / mean = 0.08%정도 나옴
# 0.1 ~ 0.3 → 보통 정도로 해석
# 그럼 평균대비 약 8%정도 흔들린다고 해석해야함. 데이터가 비교적 몰려있음

       session_time
count     20.000000
mean       5.810000
std        0.438778
min        4.800000
25%        5.575000
50%        5.850000
75%        6.125000
max        6.500000

In [ ]:
# SE및 STD구하기
# 실제 se를 구하려면 std값 / 표본개수로 구하지만
# 패키지를 사용하면 자동으로 값 구하기 가능

from statsmodels.stats.weightstats import DescrStatsW

desc = DescrStatsW(df['session_time'])

print(f'SE(표준오차) : {desc.std_mean}')
print(f'Std(표준편차) : {desc.std}') # 데이터가 대략 0.4정도 흔들림
print(f'데이터(포본)개수 : {desc.nobs}')
print(f'mean : {desc.mean}')


# 기초통계값 해석 법
# 단순 se가 0.098이 나왔다고 해서 이것만 보고 안정적인지 아닌지 판단불가
# 보통 평균대비 비율을 가장많이 확인함 >>> SE / mean
# 또는 신뢰구간(CI)를 확인

print()

print(f'평균대비 비율 : {desc.std_mean / desc.mean}') # 0.016으로 약 1.7%정도 흔들림
# 평균대비 1~2% 흔들리는 경우 꽤 안정적이라고 판단

SE(표준오차) : 0.09811379000667382
Std(표준편차) : 0.42766809560686203
데이터(포본)개수 : 20.0
mean : 5.8100000000000005

평균대비 비율 : 0.016887055078601346

In [ ]:
# 신뢰구간(CI) : 진짜 평균이 있을 것 같은 범위

# 신뢰구간 확인 이유
# 평균을 하나만 뽑지만 표본이기때문에 실제 모평균을 알 수 없음
# '때문에 이 범위 안에 있을 확률이 높다' 라는 구간을 구하는것

# 신뢰구간 95% 공식 >>> 평균 ± 1.96 × SE
# 신뢰구간 99% 공식 >>> 평균 ± 2.58 × SE

In [ ]:
from statsmodels.stats.weightstats import DescrStatsW

desc = DescrStatsW(df['session_time'])

# 아무것도 설정안하면 신뢰구간 95%로 설정
# 99%로 바꾸고싶다면 desc.tconfint_mean(alpha=0.01)로 지정
ci_low, ci_hight = desc.tconfint_mean()

print(ci_low, ci_hight)
# 실제 사용시간의 평균(모평균)은 5.6 ~ 6.0사이에 있을것이라고 확인가능

5.604645477446871 6.01535452255313

In [ ]:
# one-sample-t-test
# 우리의 평균이 특정 값(기준값)과 다른가?
# 하나의 집단 vs 기준값

# 가정 >>> 평균 체류시간이 5분인가?

In [ ]:
from scipy import stats

# popmean : 비교 기준이 되는 모집단 평균값(가설값)
# 때문에 popmean을 넣지 않으면 작동불가
# 이 데이터 평균이 어떤 값이랑 다른지 확인하는 과정이기때문
t_test, pvalue = stats.ttest_1samp(df['session_time'], popmean = 5)

print(f't값 : {t_test}')
print(f'p-value : {pvalue}')
# 0.05보다 p값이 더 작음 >>>평균이 5라는 가정 하에서는 이런 데이터가 나올 확률이 거의 없음
# 귀무가설(평균은 5분이다) 기각

# t값 = (표본평균 - popmean) / se
# t값 = 기준값 대비 얼마나 멀리 떨어졌는지 (표준화된 거리)
# 평균이 기준값(5)에서 se기준으로 8배나 멀리 떨어져있다는

t값 : 8.255720219807056
p-value : 1.0469757851631606e-07